### ISSUE TITLE
enclosure images

### ISSUE THREAD

**Issue by CokeCain** [sdepold/feedrapp#82]
has anyone managed to return images in the "enclosure" tag so far?

**Comment by sdepold** [comment]
Do you have a feed?

**Comment by CokeCain** [comment]
yes,
https://www.bug.hr/rss
i've tried adding this method but to no avail:
encl: function (t) {
                    try {
                        return t.content.match(/(<enclosure.*?>)/gi)[0].match(/link=["'](.*?)["']/)[1]
                    } catch (t) {
                        return "fail"
                    }
                }(e),

**Comment by CokeCain** [comment]
no hope?

**Comment by sdepold** [comment]
Hey. I just released a change to the feedrapp server which results in the following:

```
curl -H 'Accept: application/json' https://feedrapp.info/\?q\=https://www.bug.hr/rss | jq .

-->

{
  "responseStatus": 200,
  "responseDetails": null,
  "responseData": {
    "feed": {
      "feedUrl": "https://www.bug.hr/rss",
      "title": "bug.hr",
      "link": "https://www.bug.hr",
      "description": "Sve objave na bug.hr",
      "author": "",
      "entries": [
        {
          "title": "Izdašna donacija Odašiljača i veza za akciju Hrvatska protiv koronavirusa",
          "link": "https://www.bug.hr/dogadjaji/izdasna-donacija-odasiljaca-i-veza-za-akciju-hrvatska-protiv-koronavirusa-14652",
          "content": "Djelatnici, Uprava i Nadzorni odbor OIV-a donirali su ukupno 241.719,63 kuna za borbu protiv koronavirusa u Hrvatskoj",
          "contentSnippet": "Djelatnici, Uprava i Nadzorni odbor OIV-a donirali su ukupno 241.719,63 kuna za borbu protiv koronavirusa u Hrvatskoj",
          "publishedDate": "2020-04-08T10:43:00.000Z",
          "categories": [
            {
              "name": "Događaji"
            }
          ],
          "author": "",
          "enclosure": {
            "length": 12345,
            "type": "image/jpeg",
            "url": "https://www.bug.hr/img/izdasna-donacija-odasiljaca-i-veza-za-akciju-hrvatska-protiv-koronavirusa_0FJeMt.jpg"
          }
        },
        {
          "title": "Koronakriza usporava usvajanje EU zakona o digitalnim uslugama",
          "link": "https://www.bug.hr/biznis/koronakriza-usporava-usvajanje-eu-zakona-o-digitalnim-uslugama-14650",
          "content": "6. travnja u Bruxellesu je objavljena verzija nacrta zaključaka Vijeća za telekomunikacije EU o oblikovanju digitalne budućnosti Europe",
          "contentSnippet": "6. travnja u Bruxellesu je objavljena verzija nacrta zaključaka Vijeća za telekomunikacije EU o oblikovanju digitalne bu",
          "publishedDate": "2020-04-08T10:41:00.000Z",
          "categories": [
            {
              "name": "Biznis"
            }
          ],
          "author": "",
          "enclosure": {
            "length": 12345,
            "type": "image/jpeg",
            "url": "https://www.bug.hr/img/koronakriza-usporava-usvajanje-eu-zakona-o-digitalnim-uslugama_wTzpKQ.jpg"
          }
        },
        {
          "title": "Izvrsna ponuda! Windows 10 Pro za 10,80 eura, a Office 2016 za 22,61 eura",
          "link": "https://www.bug.hr/promo/izvrsna-ponuda-windows-10-pro-za-1080-eura-a-office-2016-za-2261-eura-14633",
          "content": "Za rad od kuće potreban vam je vrhunski softver koji možete nabaviti u intternetskoj trgovini U2KEY po izuzetno povoljni cijenama",
          "contentSnippet": "Za rad od kuće potreban vam je vrhunski softver koji možete nabaviti u intternetskoj trgovini U2KEY po izuzetno povoljni",
          "publishedDate": "2020-04-08T05:00:00.000Z",
          "categories": [
            {
              "name": "Promo"
            }
          ],
          "author": "",
          "enclosure": {
            "length": 12345,
            "type": "image/jpeg",
            "url": "https://www.bug.hr/img/izvrsna-ponuda-windows-10-pro-za-1080-eura-a-office-2016-za-2261-eura_g1gpQk.jpg"
          }
        },
        {
          "title": "Rubén Caballero prešao iz Apple u Microsoftu gdje radi na razvoju HoloLensa",
          "link": "https://www.bug.hr/osobe/ruben-caballero-presao-iz-apple-u-microsoftu-gdje-radi-na-razvoju-hololensa-14645",
          "content": "Rubén Caballero do prije godinu dana radio je u Appleu na razvoju 5G modema, a godina dana kasnije je u Microsoftu kao korporativni potpredsjednik i čovjek na čelu razvoja HoloLensa",
          "contentSnippet": "Rubén Caballero do prije godinu dana radio je u Appleu na razvoju 5G modema, a godina dana kasnije je u Microsoftu kao k",
          "publishedDate": "2020-04-08T04:30:00.000Z",
          "categories": [
            {
              "name": "Osobe"
            }
          ],
          "author": "",
          "enclosure": {
            "length": 12345,
            "type": "image/jpeg",
            "url": "https://www.bug.hr/img/ruben-caballero-presao-iz-apple-u-microsoftu-gdje-radi-na-razvoju-hololensa_sRVaGy.jpg"
          }
        }
      ]
    }
  }
}
```

As you can see, each of the entries has an enclosure property now. Please let me know if this solves your problem.

**Comment by CokeCain** [comment]
No, i still don't get the image. Tried both "url:" and "url=" This is the method i'm using:
encl: function (t) {
                    try {
                        return t.content.match(/(<enclosure.*?>)/gi)[0].match(/url:["'](.*?)["']/)[1]
                    } catch (t) {
                        return "fail"
                    }
                }(e),

**Comment by sdepold** [comment]
What is that code? What is `t`?

**Comment by sdepold** [comment]
Seems that you are looking for an enclose tag? Why? The API is returning you JSON?!

**Comment by CokeCain** [comment]
That is a snippet I added to the jquery.rss.js file. The original code to get image source from an RSS feed is:
 teaserImage: function (t) {
                    try {
                        return t.content.match(/(<img.*?>)/gi)[0]
                    } catch (t) {
                        return ""
                    }
                }(e),

**Comment by sdepold** [comment]
Please have a look at this: https://github.com/sdepold/jquery-rss/blob/master/examples/enclosure.html#L25-L41

**Comment by CokeCain** [comment]
excellent job. thank you so much <3
![image](https://user-images.githubusercontent.com/63205664/78780996-c7f98180-799f-11ea-987f-e54b705af491.png)

**Comment by sdepold** [comment]
Sweet :)
